// Copyright 2017, Google, Inc.
// Licensed under the Apache License, Version 2.0 (the 'License');
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

module.exports = [                  
    { value: "Senior Cloud Solution Architect", synonyms: [""]},
    { value: "Azure Cloud", synonyms: [""]},
    { value: "Cloud Analytical Services architectures on Azure Cloud", synonyms: [""]},
    { value: "Oracle SQL Developer", synonyms: [""]},
    { value: "Caliburn MicroMobile Development Frameworks", synonyms: [""]},
    { value: "ToolatraThe Ever Dynamic Framework World", synonyms: [""]},
    { value: "OpenZeppelin Contracts", synonyms: [""]},
    { value: "Testing Frameworks", synonyms: [""]},
    { value: "Robot Framework", synonyms: [""]},
    { value: "Galen Framework", synonyms: [""]},
    { value: "Ruby on Rails", synonyms: [""]},
    { value: "Onsen UI", synonyms: [""]},
    { value: "H2O Q", synonyms: [""]},
    { value: "jQuery Mobile", synonyms: [""]},
    { value: "Create Eth App", synonyms: [""]},
    { value: "Framework 7", synonyms: [""]},
    { value: "Fat-Free Framework", synonyms: [""]},
    { value: "Sencha Ext JS", synonyms: [""]},
    { value: "React Native", synonyms: [""]},
    { value: "Mobile Angular UI", synonyms: [""]},
    { value: "Apache Camel", synonyms: [""]},
    { value: "Apache Oozie", synonyms: [""]},
    { value: "Apache CXF", synonyms: [""]},
    { value: "Google Guava", synonyms: [""]},
    { value: "CodeName One", synonyms: [""]},
    { value: "Google Web Toolkit (GWT)", synonyms: [""]},
    { value: "Spring Roo", synonyms: [""]},
    { value: "Apache VXQuery", synonyms: [""]},
    { value: "Apache Kafka", synonyms: [""]},
    { value: "Java Collections Framework", synonyms: [""]},
    { value: "Java Media Framework", synonyms: [""]},
    { value: "Apache Tomcat", synonyms: [""]},
    { value: "Apache Uima", synonyms: [""]},
    { value: "Apache Cocoon", synonyms: [""]},
    { value: "JBoss Seam", synonyms: [""]},
    { value: "Apache Jena", synonyms: [""]},
    { value: "Apache Sling", synonyms: [""]},
    { value: "Apache Solr", synonyms: [""]},
    { value: "Apache Spark", synonyms: [""]},
    { value: "Apache Struts", synonyms: [""]},
    { value: "Spring Integration", synonyms: [""]},
    { value: "Apache Hadoop", synonyms: [""]},
    { value: "Apache Pig", synonyms: [""]},
    { value: "Apache Lucene", synonyms: [""]},
    { value: "Apache Axis", synonyms: [""]},
    { value: "Apache Giraph", synonyms: [""]},
    { value: "Oracle WebLogic", synonyms: [""]},
    { value: "Payara Server", synonyms: [""]},
    { value: "Ejml (Efficient Java Matrix Library)", synonyms: [""]},
    { value: "Apache Log4j", synonyms: [""]},
    { value: "Apache OpenNLP", synonyms: [""]},
    { value: "Apache Mina", synonyms: [""]},
    { value: "Jasper Reports", synonyms: [""]},
    { value: "Apache Shiro", synonyms: [""]},
    { value: "Java Topology suite", synonyms: [""]},
    { value: "Apache Velocity", synonyms: [""]},
    { value: "FreeMarker Template", synonyms: [""]},
    { value: "Java Astrodynamics Toolkit", synonyms: [""]},
    { value: "Direct Web Remoting", synonyms: [""]},
    { value: "Google Gson", synonyms: [""]},
    { value: "Google Guice", synonyms: [""]},
    { value: "Apache ActiveMQ", synonyms: [""]},
    { value: "Apache Qpid", synonyms: [""]},
    { value: "Apache HBase", synonyms: [""]},
    { value: "Apache Nutch", synonyms: [""]},
    { value: "Apache Geronimo", synonyms: [""]},
    { value: "Apache Pivot", synonyms: [""]},
    { value: "Apache Mahout", synonyms: [""]},
    { value: "Apache Empire DB", synonyms: [""]},
    { value: "Apache Avro", synonyms: [""]},
    { value: "Apache Felix", synonyms: [""]},
    { value: "Apache Mesos", synonyms: [""]},
    { value: "Apache River", synonyms: [""]},
    { value: "Apache Wink", synonyms: [""]},
    { value: "Apache POI", synonyms: [""]},
    { value: "Spring Security", synonyms: [""]},
    { value: "Apache Zookeeper", synonyms: [""]},
    { value: "Bouncy Castle", synonyms: [""]},
    { value: "Apache Commons", synonyms: [""]},
    { value: "Apache Xerces", synonyms: [""]},
    { value: "Apache Hive", synonyms: [""]},
    { value: "Apache Click", synonyms: [""]},
    { value: "Apache Tapestry", synonyms: [""]},
    { value: "Apache Wicket", synonyms: [""]},
    { value: "Apache Tika", synonyms: [""]},
    { value: "Apache JackRabbit", synonyms: [""]},
    { value: "Apache OODT", synonyms: [""]},
    { value: "Apache Accumulo", synonyms: [""]},
    { value: "Apache Storm", synonyms: [""]},
    { value: "Apache Samza", synonyms: [""]},
    { value: "Apache Flume", synonyms: [""]},
    { value: "Cloud Key Management", synonyms: [""]},
    { value: "Apigee API Management", synonyms: [""]},
    { value: "Cloud Build", synonyms: [""]},
    { value: "Cloud Run for Anthos", synonyms: [""]},
    { value: "Migrate to Containers", synonyms: [""]},
    { value: "Google Distributed Cloud", synonyms: [""]},
    { value: "Internet of Things (IoT)", synonyms: [""]},
    { value: "Edge TPU", synonyms: [""]},
    { value: "IoT Core", synonyms: [""]},
    { value: "Anthos Config Management", synonyms: [""]},
    { value: "Anthos Service Mesh", synonyms: [""]},
    { value: "Carbon Footprint", synonyms: [""]},
    { value: "Cloud APIs", synonyms: [""]},
    { value: "Cloud Console", synonyms: [""]},
    { value: "Cloud Mobile App", synonyms: [""]},
    { value: "Cloud Shell", synonyms: [""]},
    { value: "Config Connector", synonyms: [""]},
    { value: "Cost Management", synonyms: [""]},
    { value: "Deployment Manager", synonyms: [""]},
    { value: "Service Catalog", synonyms: [""]},
    { value: "Terraform on Google Cloud", synonyms: [""]},
    { value: "Game Servers", synonyms: [""]},
    { value: "Live Stream API", synonyms: [""]},
    { value: "Transcoder API", synonyms: [""]},
    { value: "Video Stitcher API", synonyms: [""]},
    { value: "Application migration", synonyms: [""]},
    { value: "BigQuery Data Transfer Service.", synonyms: [""]},
    { value: "Cloud Foundation Toolkit", synonyms: [""]},
    { value: "Migrate to Virtual Machines", synonyms: [""]},
    { value: "Migration Center", synonyms: [""]},
    { value: "Transfer Appliance", synonyms: [""]},
    { value: "Cloud Armor", synonyms: [""]},
    { value: "Cloud CDN", synonyms: [""]},
    { value: "Cloud Domains", synonyms: [""]},
    { value: "Cloud DNS", synonyms: [""]},
    { value: "Cloud IDS", synonyms: [""]},
    { value: "Cloud Load Balancing", synonyms: [""]},
    { value: "Cloud NAT", synonyms: [""]},
    { value: "Hybrid Connectivity", synonyms: [""]},
    { value: "Media CDN", synonyms: [""]},
    { value: "Network Connectivity Center", synonyms: [""]},
    { value: "Network Intelligence Center", synonyms: [""]},
    { value: "Network Service Tiers", synonyms: [""]},
    { value: "Private Service Connect", synonyms: [""]},
    { value: "Service Directory", synonyms: [""]},
    { value: "Traffic Director", synonyms: [""]},
    { value: "Virtual Private Cloud (VPC)", synonyms: [""]},
    { value: "Cloud Debugger", synonyms: [""]},
    { value: "Cloud Logging", synonyms: [""]},
    { value: "Cloud Monitoring", synonyms: [""]},
    { value: "Cloud Profiler", synonyms: [""]},
    { value: "Cloud Trace", synonyms: [""]},
    { value: "Cloud Error Reporting", synonyms: [""]},
    { value: "Security and Identity", synonyms: [""]},
    { value: "Advanced Protection Program", synonyms: [""]},
    { value: "Assured Workloads", synonyms: [""]},
    { value: "Binary Authorization", synonyms: [""]},
    { value: "Chronicle Security Operations", synonyms: [""]},
    { value: "Chronicle SIEM", synonyms: [""]},
    { value: "Cloud Asset Inventory", synonyms: [""]},
    { value: "Cloud Data Loss Prevention", synonyms: [""]},
    { value: "Confidential Computing", synonyms: [""]},
    { value: "Endpoint Management", synonyms: [""]},
    { value: "Packet Mirroring", synonyms: [""]},
    { value: "Risk Protection Program", synonyms: [""]},
    { value: "Secret Manager", synonyms: [""]},
    { value: "Security center", synonyms: [""]},
    { value: "Security Command Center", synonyms: [""]},
    { value: "Shielded VMs", synonyms: [""]},
    { value: "Siemplify SOAR", synonyms: [""]},
    { value: "VPC Service Controls", synonyms: [""]},
    { value: "VM Manager", synonyms: [""]},
    { value: "Certificate Authority Service", synonyms: [""]},
    { value: "Cloud Identity", synonyms: [""]},
    { value: "Identity and Access Management", synonyms: [""]},
    { value: "Identity-Aware Proxy", synonyms: [""]},
    { value: "Identity Platform", synonyms: [""]},
    { value: "Managed Service for Microsoft Active Directory", synonyms: [""]},
    { value: "Policy Intelligence", synonyms: [""]},
    { value: "Resource Manager", synonyms: [""]},
    { value: "Titan Security Key", synonyms: [""]},
    { value: "Workforce Identity Federation", synonyms: [""]},
    { value: "Web Risk", synonyms: [""]},
    { value: "App Engine", synonyms: [""]},
    { value: "Cloud Functions", synonyms: [""]},
    { value: "Storage Transfer Service", synonyms: [""]},
    { value: "Cloud Storage", synonyms: [""]},
    { value: "Cloud Storage for Firebase", synonyms: [""]},
    { value: "Google Workspace Essentials", synonyms: [""]},
    { value: "Local SSD", synonyms: [""]},
    { value: "Persistent Disk", synonyms: [""]},
    { value: "Google Cloud Backup and DR", synonyms: [""]},
    { value: "Chrome Enterprise", synonyms: [""]},
    { value: "Google Workspace", synonyms: [""]},
    { value: "Google Meet", synonyms: [""]},
    { value: "Chrome browser for your enterprise", synonyms: [""]},
    { value: "Google Maps Platform", synonyms: [""]},
    { value: "Apache Avalon", synonyms: [""]},
    { value: "Cloud Data Fusion", synonyms: [""]},
    { value: "Data Catalog", synonyms: [""]},
    { value: "Analytics Hub", synonyms: [""]},
    { value: "Looker Studio", synonyms: [""]},
    { value: "Google Marketing Platform*", synonyms: [""]},
    { value: "Cloud Life Sciences (beta)", synonyms: [""]},
    { value: "Earth Engine", synonyms: [""]},
    { value: "AlloyDB for PostgreSQL", synonyms: [""]},
    { value: "Bare Metal Solution", synonyms: [""]},
    { value: "Cloud Bigtable", synonyms: [""]},
    { value: "Cloud Spanner", synonyms: [""]},
    { value: "Cloud SQL", synonyms: [""]},
    { value: "Database Migration Service", synonyms: [""]},
    { value: "Firebase Realtime Database", synonyms: [""]},
    { value: "Artifact Registry", synonyms: [""]},
    { value: "Assured Open Source Software", synonyms: [""]},
    { value: "Cloud Code", synonyms: [""]},
    { value: "Cloud Scheduler", synonyms: [""]},
    { value: "Cloud SDK", synonyms: [""]},
    { value: "Cloud Source Repositories", synonyms: [""]},
    { value: "Cloud Tasks", synonyms: [""]},
    { value: "Cloud Workstations", synonyms: [""]},
    { value: "Container Registry", synonyms: [""]},
    { value: "Firebase Crashlytics", synonyms: [""]},
    { value: "Firebase Test Lab", synonyms: [""]},
    { value: "Google Cloud Deploy", synonyms: [""]},
    { value: "Gradle App Engine Plugin", synonyms: [""]},
    { value: "Maven App Engine Plugin", synonyms: [""]},
    { value: "Tools for Eclipse", synonyms: [""]},
    { value: "Tools for PowerShell", synonyms: [""]},
    { value: "Financial Services", synonyms: [""]},
    { value: "Payment Gateway", synonyms: [""]},
    { value: "Apigee healthcare APIx", synonyms: [""]},
    { value: "Cloud Healthcare API", synonyms: [""]},
    { value: "Device Connect for Fitbit", synonyms: [""]},
    { value: "Healthcare Natural Language AI", synonyms: [""]},
    { value: "Medical Imaging Suite", synonyms: [""]},
    { value: "Google Kubernetes Engine", synonyms: [""]},
    { value: "Cloud Run", synonyms: [""]},
    { value: "Vertex AI", synonyms: [""]},
    { value: "Vertex AI Workbench", synonyms: [""]},
    { value: "Vertex Explainable AI", synonyms: [""]},
    { value: "Media Translation", synonyms: [""]},
    { value: "Natural Language AI", synonyms: [""]},
    { value: "Recommendations AI", synonyms: [""]},
    { value: "Speech-to-Text", synonyms: [""]},
    { value: "Text-to-Speech", synonyms: [""]},
    { value: "Translation AI", synonyms: [""]},
    { value: "Video AI", synonyms: [""]},
    { value: "Vision AI", synonyms: [""]},
    { value: "AI Infrastructure", synonyms: [""]},
    { value: "Cloud GPUs", synonyms: [""]},
    { value: "Cloud TPUs", synonyms: [""]},
    { value: "Deep Learning VM Image", synonyms: [""]},
    { value: "Deep Learning Containers", synonyms: [""]},
    { value: "TensorFlow Enterprise", synonyms: [""]},
    { value: "Contact Center AI", synonyms: [""]},
    { value: "Document AI", synonyms: [""]},
    { value: "Intelligent products (Preview)", synonyms: [""]},
    { value: "Product Discovery", synonyms: [""]},
    { value: "Apigee API Platform", synonyms: [""]},
    { value: "Apigee Integration", synonyms: [""]},
    { value: "Apigee Hybrid", synonyms: [""]},
    { value: "AppSheet Automation", synonyms: [""]},
    { value: "Apigee Open Banking APIx", synonyms: [""]},
    { value: "Apigee Sense", synonyms: [""]},
    { value: "API Gateway", synonyms: [""]},
    { value: "Compute Engine", synonyms: [""]},
    { value: "Spot VMs", synonyms: [""]},
    { value: "Sole-tenant Nodes", synonyms: [""]},
    { value: "SQL Server on Google Cloud", synonyms: [""]},
    { value: "VMware Engine", synonyms: [""]},
    { value: "Container Security", synonyms: [""]},
    { value: "Google Kubernetes Engine (GKE)", synonyms: [""]},
    { value: "Kubernetes applications on Google Cloud Marketplace", synonyms: [""]},
    { value: "Cloud Composer", synonyms: [""]},
    { value: "Data Modeling", synonyms: [""]},
    { value: "Data visualization", synonyms: [""]},
    { value: "Data Protection", synonyms: [""]},
    { value: "Data entry", synonyms: [""]},
    { value: "Data Warehousing", synonyms: [""]},
    { value: "Data Integration", synonyms: [""]},
    { value: "Data Collection and Analysis", synonyms: [""]},
    { value: "Data Storage", synonyms: [""]},
    { value: "Data Architecture", synonyms: [""]},
    { value: "Data Governance", synonyms: [""]},
    { value: "Data Software Engineering", synonyms: [""]},
    { value: "Data Security", synonyms: [""]},
    { value: "Data Transformation Concepts", synonyms: [""]},
    { value: "Data Preparation", synonyms: [""]},
    { value: "QA Director", synonyms: [""]},
    { value: "QaSpace - Test Management", synonyms: [""]},
    { value: "CA Lisa QA Automation Framework", synonyms: [""]},
    { value: "Web Analytics quality assurance (QA) testing", synonyms: [""]},
    { value: "Security QA in Embedded", synonyms: [""]},
    { value: "Automated QA solutions development for Web Analytics", synonyms: [""]},
    { value: "DLT Quality Assurance", synonyms: [""]},
    { value: "Academic content authoring", synonyms: [""]},
    { value: "Market Research", synonyms: [""]},
    { value: "User Research", synonyms: [""]},
    { value: "Operations Research", synonyms: [""]},
    { value: "Research Methods", synonyms: [""]},
    { value: "Focus groups", synonyms: [""]},
    { value: "Desk Research", synonyms: [""]},
    { value: "Survey Research", synonyms: [""]},
    { value: "Talent Research", synonyms: [""]},
    { value: "Domain Research", synonyms: [""]},
    { value: "Visual Research", synonyms: [""]},
    { value: "Research Planning", synonyms: [""]},
    { value: "Sociological Research", synonyms: [""]},
    { value: "Research [Financial Services]", synonyms: [""]},
    { value: "Market Data Research", synonyms: [""]},
    { value: "Competitor Evaluation", synonyms: [""]},
    { value: "KPI analysis", synonyms: [""]},
    { value: "Guerrilla User Research", synonyms: [""]},
    { value: "Product Management", synonyms: [""]},
    { value: "Product Architecture", synonyms: [""]},
    { value: "Product Development", synonyms: [""]},
    { value: "Product Ownership", synonyms: [""]},
    { value: "Product Launch", synonyms: [""]},
    { value: "Product metrics", synonyms: [""]},
    { value: "Product Life Cycle", synonyms: [""]},
    { value: "Product Retirement", synonyms: [""]},
    { value: "Product discovery", synonyms: [""]},
    { value: "Product Analytics", synonyms: [""]},
    { value: "Product Visioning", synonyms: [""]},
    { value: "MVP Product Definitions", synonyms: [""]},
    { value: "Digital Business/Product Strategy", synonyms: [""]},
    { value: "Manage minimum viable product", synonyms: [""]},
    { value: "Product success measuring", synonyms: [""]},
    { value: "Product Strategy Development", synonyms: [""]},
    { value: "Product Master", synonyms: [""]},
    { value: "Sitecore Product Content Management", synonyms: [""]},
    { value: "Platform & Product Strategy", synonyms: [""]},
    { value: "Online Education", synonyms: [""]},
    { value: "Executive Education", synonyms: [""]},
    { value: "Higher Education", synonyms: [""]},
    { value: "Enterprise Education & Learning", synonyms: [""]},
    { value: "K-12 Education", synonyms: [""]},
    { value: "Designing learning solutions", synonyms: [""]},
    { value: "RD Education Delivery", synonyms: [""]},
    { value: "Salesforce Education Cloud", synonyms: [""]},
    { value: "SAP-IS: Higher Education Research", synonyms: [""]},
    { value: "Education [CSR]", synonyms: [""]},
    { value: "Site Reliability Engineering", synonyms: [""]},
    { value: "Azure Site Recovery", synonyms: [""]},
    { value: "Site Improve", synonyms: [""]},
    { value: "ATG Site Admin 10", synonyms: [""]},
    { value: "Sitecore Multi Site Management", synonyms: [""]},
    { value: "Multi-site drupal", synonyms: [""]},
    { value: "Static site generators", synonyms: [""]},
    { value: "AEM Multi Site Manager and Language Copies", synonyms: [""]},
    { value: "Interwoven\'s Team Site and Open Deploy", synonyms: [""]},
    { value: "Multi-site in Drupal core - concepts", synonyms: [""]},
    { value: "Multi-site in Drupal core - environment configuration", synonyms: [""]},
    { value: "Multi-site in Drupal core - Organic Groups module", synonyms: [""]},
    { value: "Multi-site in Drupal core - Domain Access module", synonyms: [""]},
    { value: "Excess Liability Insurance", synonyms: [""]},
    { value: "SAP Test Suite", synonyms: [""]},
    { value: "Adobe AEM - Sites & Assets", synonyms: [""]},
    { value: "Oracle E-Business Suite", synonyms: [""]},
    { value: "Security Operation Design", synonyms: [""]},
    { value: "Information Security", synonyms: [""]},
    { value: "DBMS Security", synonyms: [""]},
    { value: "Application Security", synonyms: [""]},
    { value: "Network Security", synonyms: [""]},
    { value: "Security Vulnerabilities", synonyms: [""]},
    { value: "Java Security", synonyms: [""]},
    { value: "Security Incident Management", synonyms: [""]},
    { value: "Big Data Security", synonyms: [""]},
    { value: "Physical security", synonyms: [""]},
    { value: "Security Standards", synonyms: [""]},
    { value: "Security assessment", synonyms: [""]},
    { value: "Security Architecture", synonyms: [""]},
    { value: "JavaScript security", synonyms: [""]},
    { value: "Email Security", synonyms: [""]},
    { value: "Database Security", synonyms: [""]},
    { value: "Embedded System Security", synonyms: [""]},
    { value: "Game Design", synonyms: [""]},
    { value: "Game Theory", synonyms: [""]},
    { value: "Game testing", synonyms: [""]},
    { value: "Game Production", synonyms: [""]},
    { value: "Game Console", synonyms: [""]},
    { value: "Games Functional Testing", synonyms: [""]},
    { value: "Games localization", synonyms: [""]},
    { value: "Game Maker Studio", synonyms: [""]},
    { value: "Game Item Art: Implementation in 2D or 3D", synonyms: [""]},
    { value: "Games Salad", synonyms: [""]},
    { value: "Immersive Experience", synonyms: [""]},
    { value: "Mobile Game Development", synonyms: [""]},
    { value: "C++ Games Development", synonyms: [""]},
    { value: "C# Games Development", synonyms: [""]},
    { value: "Collaborative Games", synonyms: [""]},
    { value: ".NET Game Development", synonyms: [""]},
    { value: "Unity 3d Game Development", synonyms: [""]},
    { value: "Custom 2D game engine development", synonyms: [""]},
    { value: "Desktop Game Development", synonyms: [""]},
    { value: "Executive Interviews", synonyms: [""]},
    { value: "Executive Workshops", synonyms: [""]},
    { value: "Executive Dashboards", synonyms: [""]},
    { value: "Executive communications", synonyms: [""]},
    { value: "Executive S&OP", synonyms: [""]},
    { value: "SAP-EC: Executive Information System (EC-EIS)", synonyms: [""]},
    { value: "Vendor Management", synonyms: [""]},
    { value: "Government Services", synonyms: [""]},
    { value: "Vendor Assessment", synonyms: [""]},
    { value: "Energy sector", synonyms: [""]},
    { value: "Execution Management Financial Systems", synonyms: [""]},
    { value: "Mentor Graphics", synonyms: [""]},
    { value: "Supplier/Vendor Relationship Management", synonyms: [""]},
    { value: "Program Executing", synonyms: [""]},
    { value: "Best Execution", synonyms: [""]},
    { value: "Manufacturing Execution Systems", synonyms: [""]},
    { value: "Order execution management", synonyms: [""]},
    { value: "Blockchain Tools", synonyms: [""]},
    { value: "Blockchain Platforms", synonyms: [""]},
    { value: "Blockchain Interoperability", synonyms: [""]},
    { value: "Blockchain Payment Technologies", synonyms: [""]},
    { value: "Cryptocurrency & Blockchain [FinTech]", synonyms: [""]},
    { value: "Amazon Managed Blockchain", synonyms: [""]},
    { value: "Oracle Blockchain", synonyms: [""]},
    { value: "SAP Blockchain", synonyms: [""]},
    { value: "Sales and Marketing", synonyms: [""]},
    { value: "Salesforce Sales Cloud", synonyms: [""]},
    { value: "Salesforce Primary Clouds (Sales Cloud, Service Cloud, Community Cloud)", synonyms: [""]},
    { value: "Sales Effectiveness", synonyms: [""]},
    { value: "Salesforce Apex", synonyms: [""]},
    { value: "Sales and Lead Management", synonyms: [""]},
    { value: "Sales and Markering metrics analysis", synonyms: [""]},
    { value: "Salesforce (Other)", synonyms: [""]},
    { value: "Salesforce platform", synonyms: [""]},
    { value: "Salesforce (Other - DEP)", synonyms: [""]},
    { value: "Salesforce Commerce Cloud (B2C - Demandware, Javascript)", synonyms: [""]},
    { value: "Sales Information System", synonyms: [""]},
    { value: "Salesforce Marketing Cloud (ExactTarget)/Pardot", synonyms: [""]},
    { value: "Sales & Operations Planning", synonyms: [""]},
    { value: "Salesforce Service Cloud", synonyms: [""]},
    { value: "Salesforce Marketing Cloud", synonyms: [""]},
    { value: "MS Windows XP Embedded Studio", synonyms: [""]},
    { value: "Mobile Applications", synonyms: [""]},
    { value: "Planning - SAP BPC 10.1 NW Embedded", synonyms: [""]},
    { value: "Project Manager in Presales", synonyms: [""]},
    { value: "Project Management", synonyms: [""]},
    { value: "Project planning", synonyms: [""]},
    { value: "MS Project", synonyms: [""]},
    { value: "Project Initiation", synonyms: [""]},
    { value: "Project Administration", synonyms: [""]},
    { value: "Project Closure", synonyms: [""]},
    { value: "Project budgeting", synonyms: [""]},
    { value: "Project estimations", synonyms: [""]},
    { value: "Project Build", synonyms: [""]},
    { value: "Project Assignment", synonyms: [""]},
    { value: "Project Reactor", synonyms: [""]},
    { value: "Project Rollout", synonyms: [""]},
    { value: "Digital Project Management", synonyms: [""]},
    { value: "Project Client Relationship", synonyms: [""]},
    { value: "Project Discovery", synonyms: [""]},
    { value: "Yocto Project", synonyms: [""]},
    { value: "Project Team Management", synonyms: [""]},
    { value: "Project Operational Excellence", synonyms: [""]},
    { value: "Design patterns", synonyms: [""]},
    { value: "Oracle Designer", synonyms: [""]},
    { value: "Sybase Power Designer / Quest Designer", synonyms: [""]},
    { value: "UX Design", synonyms: [""]},
    { value: "Graphic design", synonyms: [""]},
    { value: "Design thinking", synonyms: [""]},
    { value: "Level Design", synonyms: [""]},
    { value: "Adobe designer", synonyms: [""]},
    { value: "Visual Design", synonyms: [""]},
    { value: "Software Design", synonyms: [""]},
    { value: "Affinity Designer", synonyms: [""]},
    { value: "Altium Designer", synonyms: [""]},
    { value: "Google Web Designer", synonyms: [""]},
    { value: "Interaction Design", synonyms: [""]},
    { value: "User Interface Design", synonyms: [""]},
    { value: "Microsoft Office SharePoint Designer 2010", synonyms: [""]},
    { value: "Instructional Design", synonyms: [""]},
    { value: "Microsoft Office SharePoint Designer 2007", synonyms: [""]},
    { value: "Service Design", synonyms: [""]},
    { value: "Big Data", synonyms: [""]},
    { value: "Data Analysis", synonyms: [""]},
    { value: "Big Data Data Management", synonyms: [""]},
    { value: "Data Science", synonyms: [""]},
    { value: "Data Quality", synonyms: [""]},
    { value: "Data Management", synonyms: [""]},
    { value: "Data Mining", synonyms: [""]},
    { value: "Spring Data", synonyms: [""]},
    { value: "Market Data", synonyms: [""]},
    { value: "Big Data Data Visualisation", synonyms: [""]},
    { value: "Machine Learning Studio", synonyms: [""]},
    { value: "Machine Learning Engineering", synonyms: [""]},
    { value: "Machine Learning Model Development", synonyms: [""]},
    { value: "Machine Learning Tools", synonyms: [""]},
    { value: "Azure Machine Learning", synonyms: [""]},
    { value: "SAP Machine Learning", synonyms: [""]},
    { value: "Machine Learning on Graph Data", synonyms: [""]},
    { value: "Machine Learning with BigData", synonyms: [""]},
    { value: "Additive Machine Learning Models", synonyms: [""]},
    { value: "Clustering Metrics for Machine Learning", synonyms: [""]},
    { value: "Regression Metrics for Machine Learning", synonyms: [""]},
    { value: "Statistics and Machine Learning Toolbox", synonyms: [""]},
    { value: "Azure AI + Machine Learning", synonyms: [""]},
    { value: "Ranking Metrics for Machine Learning", synonyms: [""]},
    { value: "Classification Metrics for Machine Learning", synonyms: [""]},
    { value: "GCP AI and Machine Learning", synonyms: [""]},
    { value: "Factorization-based Machine Learning Models", synonyms: [""]},
    { value: "Tree-based Machine Learning Models", synonyms: [""]},
    { value: "GRC Machine Learning & AI Technology", synonyms: [""]},
    { value: "E-Learning').tag('OneWordSkill')", synonyms: [""]},
    { value: "Business Analysis", synonyms: [""]},
    { value: "Business Development", synonyms: [""]},
    { value: "Business Correspondence", synonyms: [""]},
    { value: "Business Acumen", synonyms: [""]},
    { value: "Business Applications", synonyms: [""]},
    { value: "Business Transformation", synonyms: [""]},
    { value: "Business Architecture", synonyms: [""]},
    { value: "Business Strategy", synonyms: [""]},
    { value: "Business Consulting", synonyms: [""]},
    { value: "Business continuity", synonyms: [""]},
    { value: "Business Rules Analysis", synonyms: [""]},
    { value: "Business cases", synonyms: [""]},
    { value: "Business need definition", synonyms: [""]},
    { value: "Business Communication", synonyms: [""]},
    { value: "Business Studio", synonyms: [""]},
    { value: "Business analysis activities planning", synonyms: [""]},
    { value: "Data and Business Analysis", synonyms: [""]},
    { value: "Business Design", synonyms: [""]},
    { value: "Business capability analysis", synonyms: [""]},
    { value: "Business Travel", synonyms: [""]},
    { value: "Database Administration", synonyms: [""]},
    { value: "Database Performance", synonyms: [""]},
    { value: "Database Testing", synonyms: [""]},
    { value: "Database Structure", synonyms: [""]},
    { value: "Database concepts", synonyms: [""]},
    { value: "Database Configuration and Maintenance", synonyms: [""]},
    { value: "Database Performance Tuning", synonyms: [""]},
    { value: "Database Knowledge and SQL Proficiency", synonyms: [""]},
    { value: "Database Performance Profiling", synonyms: [""]},
    { value: "Database Management and Operations", synonyms: [""]},
    { value: "Database Monitoring Implementation and Maintenance", synonyms: [""]},
    { value: "Databases Performance Testing", synonyms: [""]},
    { value: "Database Toolbox", synonyms: [""]},
    { value: "Databases in Quantitative Analysis", synonyms: [""]},
    { value: "Database Rider", synonyms: [""]},
    { value: "Database Access and Reporting", synonyms: [""]},
    { value: "Databases experience", synonyms: [""]},
    { value: "System Testing", synonyms: [""]},
    { value: "System Analysis", synonyms: [""]},
    { value: "System Integration Testing", synonyms: [""]},
    { value: "System validation", synonyms: [""]},
    { value: "System troubleshooting", synonyms: [""]},
    { value: "System Administration", synonyms: [""]},
    { value: "Conversational Monitor System", synonyms: [""]},
    { value: "System modeling", synonyms: [""]},
    { value: "System analysis and System Architecture design", synonyms: [""]},
    { value: "Microsoft System Center", synonyms: [""]},
    { value: "Debian Packaging System", synonyms: [""]},
    { value: "WinCE system", synonyms: [""]},
    { value: "System Controlling", synonyms: [""]},
    { value: "System-on-chip", synonyms: [""]},
    { value: "Computerized System Validation", synonyms: [""]},
    { value: "Reuters Market Data System", synonyms: [""]},
    { value: "Building management system", synonyms: [""]},
    { value: "OMS System", synonyms: [""]},
    { value: "X Window System", synonyms: [""]},
    { value: "Embedded Systems", synonyms: [""]},
    { value: "Embedded Computer Languages", synonyms: [""]},
    { value: "Embedded testing", synonyms: [""]},
    { value: "Embedded Platforms", synonyms: [""]},
    { value: "Windows Embedded", synonyms: [""]},
    { value: "AT/Embedded", synonyms: [""]},
    { value: "Embedded Coder", synonyms: [""]},
    { value: "Embedded Software Testing", synonyms: [""]},
    { value: "Embedded Systems Design", synonyms: [""]},
    { value: "Embedded Computing", synonyms: [""]},
    { value: "Power BI Embedded", synonyms: [""]},
    { value: "Flutter Embedded", synonyms: [""]},
    { value: "Testing in Embedded", synonyms: [""]},
    { value: "Work with Embedded content", synonyms: [""]},
    { value: "Bank law", synonyms: [""]},
    { value: "Estimation and Work Planning", synonyms: [""]},
    { value: "Mortgage and Title Insurance", synonyms: [""]},
    { value: "Mobile Banking", synonyms: [""]},
    { value: "Mobile web", synonyms: [""]},
    { value: "Mobile OS", synonyms: [""]},
    { value: "Mobile Standards", synonyms: [""]},
    { value: "Mobile Native", synonyms: [""]},
    { value: "Mobile Strategy", synonyms: [""]},
    { value: "Mobile Cloud", synonyms: [""]},
    { value: "Mobile Test Automation Tools", synonyms: [""]},
    { value: "Mobile Products  [Travel Solutions]", synonyms: [""]},
    { value: "Mobile Test Automation", synonyms: [""]},
    { value: "Mobile BI", synonyms: [""]},
    { value: "Mobile Security Testing", synonyms: [""]},
    { value: "Mobile web.iUI", synonyms: [""]},
    { value: "Mobile APIs", synonyms: [""]},
    { value: "Mobile Tools", synonyms: [""]},
    { value: "Mobile Payments", synonyms: [""]},
    { value: "Mobile Applications Performance Testing", synonyms: [""]},
    { value: "DevOps Insight Engine", synonyms: [""]},
    { value: "Azure DevOps", synonyms: [""]},
    { value: "DevOps for DLT", synonyms: [""]},
    { value: "Azure DevOps Server", synonyms: [""]},
    { value: "Data DevOps", synonyms: [""]},
    { value: "Azure DevOps Services", synonyms: [""]},
    { value: "SAP Basis and DevOps", synonyms: [""]},
    { value: "Writing DevOps Documentation", synonyms: [""]},
    { value: "Drupal DevOps", synonyms: [""]},
    { value: "Amazon DevOps Guru", synonyms: [""]},
    { value: "AEM DevOps", synonyms: [""]},
    { value: "Sitecore DevOps", synonyms: [""]},
    { value: "Data & Analytics Development Support", synonyms: [""]},
    { value: "Cloud Support Services", synonyms: [""]},
    { value: "Cloud Foundry", synonyms: [""]},
    { value: "Cloud Platforms", synonyms: [""]},
    { value: "Cloud Data Services", synonyms: [""]},
    { value: "Cloud Operations", synonyms: [""]},
    { value: "Cloud Fundamentals", synonyms: [""]},
    { value: "Cloud Computing Best Practices", synonyms: [""]},
    { value: "Cloud Transformation", synonyms: [""]},
    { value: "Cloud Computing basics", synonyms: [""]},
    { value: "Cloud Infrastructure Provisioning", synonyms: [""]},
    { value: "Cloud Data Engineering", synonyms: [""]},
    { value: "Cloudera Products and Solutions", synonyms: [""]},
    { value: "Cloud Data Analytics", synonyms: [""]},
    { value: "IBM Rational Application Developer", synonyms: [""]},
    { value: "GCP Developer Tools", synonyms: [""]},
    { value: "WebSphere Studio Application Developer", synonyms: [""]},
    { value: "Salesforce Developer Console", synonyms: [""]},
    { value: "Azure Developer Tools", synonyms: [""]},
    { value: "IBM WebSphere Integration Developer", synonyms: [""]},
    { value: "Oracle SQL Developer Data Modeler", synonyms: [""]},
    { value: "Apigee Developer Portal", synonyms: [""]},
    { value: "Microsoft Teams developer platform", synonyms: [""]},
    { value: "Salesforce Developer Tools", synonyms: [""]},
    { value: "iOS Testing for Developers", synonyms: [""]},
    { value: "Writing Developers-oriented Documentation", synonyms: [""]},
    { value: "Datastax Apache Cassandra Developer", synonyms: [""]},
    { value: "IBM Rational Developer for i", synonyms: [""]},
    { value: "Full-text Search Technologies", synonyms: [""]},
    { value: "ASIC design - Full custom design", synonyms: [""]},
    { value: "Elastic Stack", synonyms: [""]},
    { value: "JAM Stack", synonyms: [""]},
    { value: "Cross-stack Engineering", synonyms: [""]},
    { value: "Azure Stack Edge", synonyms: [""]},
    { value: "Stock Exchange", synonyms: [""]},
    { value: "AEM Technology Stack", synonyms: [""]},
    { value: "CPU stack", synonyms: [""]},
    { value: "Threat Stack", synonyms: [""]},
    { value: "Azure Stack Hub", synonyms: [""]},
    { value: "Azure Stack HCI", synonyms: [""]},
    { value: "SciSharp STACK", synonyms: [""]},
    { value: "Product - Fuel", synonyms: [""]},
    { value: "Azure Stack Development Kit", synonyms: [""]},
    { value: "Azure Stack Family", synonyms: [""]},
    { value: "Javascript Backend Platform", synonyms: [""]},
    { value: "Mortage-Backend Securities", synonyms: [""]},
    { value: "Consumer Package Goods", synonyms: [""]},
    { value: ".NET Back-end Development", synonyms: [""]},
    { value: "Back Office Trading Applications", synonyms: [""]},
    { value: "Back-office [FS Institutions]", synonyms: [""]},
    { value: "Travel Back- and Mid-Office", synonyms: [""]},
    { value: "Java Development", synonyms: [""]},
    { value: "Front-End Development", synonyms: [""]},
    { value: ".NET Web Development", synonyms: [""]},
    { value: "Governance, Risk and Compliance", synonyms: [""]},
    { value: "Change management", synonyms: [""]},
    { value: "Teamwork and Collaboration", synonyms: [""]},
    { value: "Visa Standards and Protocols", synonyms: [""]},
    { value: "Oracle Developer", synonyms: [""]},
    { value: "PL/SQL Developer", synonyms: [""]},
    { value: "SAP-SD: Sales and Distribution: Billing", synonyms: [""]},
    { value: "ASP.NET/ASP.NET Core", synonyms: [""]},
    { value: "Electronic Engineering", synonyms: [""]},
    { value: "Post Grade Studies", synonyms: [""]},
    { value: "Computer Programmer Engineer", synonyms: [""]},
    { value: "Information Systems Manager", synonyms: [""]},
    { value: "Software Engineer", synonyms: [""]},
    { value: "Web Developer Engineer", synonyms: [""]},
    { value: "Software Design Engineer", synonyms: [""]},
    { value: "Software System Applications", synonyms: [""]},
    { value: "Database Management Engineer", synonyms: [""]},
    { value: "Network Systems Engineer", synonyms: [""]},
    { value: "Computer Systems Manager", synonyms: [""]},
    { value: "Cyber Security Engineer", synonyms: [""]},
    { value: "Computer Systems Analyst", synonyms: [""]},
    { value: "Information Security Analysts", synonyms: [""]},
    { value: "Network Systems Administrators", synonyms: [""]},
    { value: "Master\'s Degree in Software Engineering", synonyms: [""]},
    { value: "Computer Network Architects Engineer", synonyms: [""]},
    { value: "Software Developer Manager Engineer", synonyms: [""]},
    { value: "Senior Software Engineer", synonyms: [""]},
    { value: "Solutions Architect Engineer", synonyms: [""]},
    { value: "Doctoral Degree in Software Engineering", synonyms: [""]},
    { value: "Research Scientist", synonyms: [""]},
    { value: "Civil engineer", synonyms: [""]},
    { value: "Mechanical engineer", synonyms: [""]},
    { value: "Chemical engineer", synonyms: [""]},
    { value: "Biological engineer", synonyms: [""]},
    { value: "Nuclear engineer", synonyms: [""]},
    { value: "Aerospace engineer", synonyms: [""]},
    { value: "Electrical engineer", synonyms: [""]},
    { value: "Environmental engineer", synonyms: [""]},
    { value: "Geological engineer", synonyms: [""]},
    { value: "Marine engineer", synonyms: [""]},
    { value: "Petroleum engineer", synonyms: [""]},
    { value: "Safety engineer", synonyms: [""]},
    { value: "Product engineer", synonyms: [""]},
    { value: "Compliance engineer", synonyms: [""]},
    { value: "Senior process engineer", synonyms: [""]},
    { value: "UX designer", synonyms: [""]},
    { value: "UI developer", synonyms: [""]},
    { value: "IT manager", synonyms: [""]},
    { value: "Computer programmer", synonyms: [""]},
    { value: "SQL developer", synonyms: [""]},
    { value: "Software developer", synonyms: [""]},
    { value: "Web administrator", synonyms: [""]},
    { value: "Data architect", synonyms: [""]},
    { value: "Business intelligence developer", synonyms: [""]},
    { value: "Mobile application developer", synonyms: [""]},
    { value: "Information security analyst", synonyms: [""]},
    { value: "Front-end web developer", synonyms: [""]},
    { value: "Java developer", synonyms: [""]},
    { value: "Database manager", synonyms: [""]},
    { value: "Software engineer", synonyms: [""]},
    { value: "Web Development", synonyms: [""]},
    { value: "React JS", synonyms: [""]},
    { value: "Vue JS", synonyms: [""]},
    { value: "ASP.NET Core", synonyms: [""]},
    { value: "Front End Web Development", synonyms: [""]},
    { value: "Full Stack Web Development", synonyms: [""]},
    { value: "Web Design", synonyms: [""]},
    { value: "REST API", synonyms: [""]},
    { value: "Spring Boot", synonyms: [""]},
    { value: "MERN StackTopic", synonyms: [""]},
    { value: "Machine Learning", synonyms: [""]},
    { value: "Artificial Intelligence", synonyms: [""]},
    { value: "Deep Learning", synonyms: [""]},
    { value: "Natural Language Processing", synonyms: [""]},
    { value: "Neural Networks", synonyms: [""]},
    { value: "Data Visualization", synonyms: [""]},
    { value: "Computer Vision", synonyms: [""]},
    { value: "Reinforcement Learning", synonyms: [""]},
    { value: "Regression Analysis", synonyms: [""]},
    { value: "Object Detection", synonyms: [""]},
    { value: "Web Scraping", synonyms: [""]},
    { value: "Android Development", synonyms: [""]},
    { value: "iOS Development", synonyms: [""]},
    { value: "Google Flutter", synonyms: [""]},
    { value: "App Development", synonyms: [""]},
    { value: "Xamarin.Forms", synonyms: [""]},
    { value: "Android Studio", synonyms: [""]},
    { value: "Mobile App Design", synonyms: [""]},
    { value: "Augmented Reality", synonyms: [""]},
    { value: "Apple Watch Development", synonyms: [""]},
    { value: "Android Jetpack", synonyms: [""]},
    { value: "App Inventor 2", synonyms: [""]},
    { value: "Mobile App Business", synonyms: [""]},
    { value: "iOS Game Development", synonyms: [""]},
    { value: "Programming Fundamentals", synonyms: [""]},
    { value: "Object Oriented Programming", synonyms: [""]},
    { value: "Scratch Programming", synonyms: [""]},
    { value: "Functional Programming", synonyms: [""]},
    { value: "Data Structures", synonyms: [""]},
    { value: "Python GUI", synonyms: [""]},
    { value: "Excel VBA", synonyms: [""]},
    { value: "Python Scripting", synonyms: [""]},
    { value: "Game Development Fundamentals", synonyms: [""]},
    { value: "Unreal Engine", synonyms: [""]},
    { value: "2D Game Development", synonyms: [""]},
    { value: "3D Game Development", synonyms: [""]},
    { value: "Construct Game Engine", synonyms: [""]},
    { value: "GameMaker Studio", synonyms: [""]},
    { value: "Unreal Engine Blueprints", synonyms: [""]},
    { value: "Python Game Development", synonyms: [""]},
    { value: "Android Game Development", synonyms: [""]},
    { value: "Virtual Reality", synonyms: [""]},
    { value: "ROBLOX Game Development", synonyms: [""]},
    { value: "Coding For Kids", synonyms: [""]},
    { value: "SQL Server", synonyms: [""]},
    { value: "Oracle SQL", synonyms: [""]},
    { value: "Database Design", synonyms: [""]},
    { value: "PostgreSQL", synonyms: [""]},
    { value: "Oracle Database", synonyms: [""]},
    { value: "Database Management", synonyms: [""]},
    { value: "Database Programming", synonyms: [""]},
    { value: "FileMaker", synonyms: [""]},
    { value: "Microsoft SQL", synonyms: [""]},
    { value: "Microsoft Azure", synonyms: [""]},
    { value: "Business Intelligence", synonyms: [""]},
    { value: "Data Warehouse", synonyms: [""]},
    { value: "Amazon AWS", synonyms: [""]},
    { value: "Apache Cassandra", synonyms: [""]},
    { value: "Software Testing", synonyms: [""]},
    { value: "Automation Testing", synonyms: [""]},
    { value: "Selenium Testing Framework", synonyms: [""]},
    { value: "Selenium WebDriver", synonyms: [""]},
    { value: "API Testing", synonyms: [""]},
    { value: "Unit Testing", synonyms: [""]},
    { value: "Performance Testing", synonyms: [""]},
    { value: "Quality Assurance", synonyms: [""]},
    { value: "REST Assured", synonyms: [""]},
    { value: "Mobile Testing", synonyms: [""]},
    { value: "Cucumber Software", synonyms: [""]},
    { value: "BDD Behavior Driven Development", synonyms: [""]},
    { value: "ISTQB Certified Tester Foundation Level", synonyms: [""]},
    { value: "HP UFT/QTP", synonyms: [""]},
    { value: "Coding Interview", synonyms: [""]},
    { value: "Software Engineering", synonyms: [""]},
    { value: "Design Patterns", synonyms: [""]},
    { value: "Software Architecture", synonyms: [""]},
    { value: "Software Development", synonyms: [""]},
    { value: "SOLID Principles", synonyms: [""]},
    { value: "Robot Operating System", synonyms: [""]},
    { value: "Apache Maven", synonyms: [""]},
    { value: "Developer Tools", synonyms: [""]},
    { value: "Internet Of Things", synonyms: [""]},
    { value: "Visual Studio Code", synonyms: [""]},
    { value: "Salesforce Lightning", synonyms: [""]},
    { value: "Version Control", synonyms: [""]},
    { value: "Vim Text Editor", synonyms: [""]},
    { value: "Spring Framework", synonyms: [""]},
    { value: "Entity Framework", synonyms: [""]},
    { value: "Articulate Storyline", synonyms: [""]},
    { value: "Bubble Visual Programming", synonyms: [""]},
    { value: "WordPress for Ecommerce", synonyms: [""]},
    { value: "Microsoft Power Apps", synonyms: [""]},
    { value: "Google AppSheet", synonyms: [""]},
    { value: "Mobile App Development", synonyms: [""]},
    { value: "Microsoft Power Automate", synonyms: [""]},
    { value: "Google Blogger", synonyms: [""]},
    { value: "Salesforce Development", synonyms: [""]},
    { value: "WordPress Plugins", synonyms: [""]},
    { value: "Microsoft Certification", synonyms: [""]},
    { value: "AWS Certification", synonyms: [""]},
    { value: "Oracle Certification", synonyms: [""]},
    { value: "Cisco CCNA", synonyms: [""]},
    { value: "Microsoft AZ-900", synonyms: [""]},
    { value: "Google Cloud Certification", synonyms: [""]},
    { value: "AWS Certified Cloud Practitioner", synonyms: [""]},
    { value: "AWS Certified Solutions Architect - Associate", synonyms: [""]},
    { value: "Professional Scrum Master", synonyms: [""]},
    { value: "CompTIA A+", synonyms: [""]},
    { value: "CISSP - Certified Information Systems Security Professional", synonyms: [""]},
    { value: "CCNP Enterprise", synonyms: [""]},
    { value: "ITIL 4 Foundation", synonyms: [""]},
    { value: "CompTIA Security+", synonyms: [""]},
    { value: "Microsoft AZ-104", synonyms: [""]},
    { value: "SAP Certified Application Associate - SAP S/4HANA", synonyms: [""]},
    { value: "AWS Certified Developer - Associate", synonyms: [""]},
    { value: "Google Cloud Associate Cloud Engineer", synonyms: [""]},
    { value: "ServiceNow Certified System Administrator", synonyms: [""]},
    { value: "Salesforce Certified Administrator", synonyms: [""]},
    { value: "CompTIA Network+", synonyms: [""]},
    { value: "Ethical Hacking", synonyms: [""]},
    { value: "Cyber Security", synonyms: [""]},
    { value: "Penetration Testing", synonyms: [""]},
    { value: "Computer Network", synonyms: [""]},
    { value: "Kali Linux", synonyms: [""]},
    { value: "IT Networking Fundamentals", synonyms: [""]},
    { value: "Cyber Security Awareness", synonyms: [""]},
    { value: "Wireshark", synonyms: [""]},
    { value: "Network Engineering", synonyms: [""]},
    { value: "Network Monitoring", synonyms: [""]},
    { value: "Computer Forensics", synonyms: [""]},
    { value: "Bug Bounty", synonyms: [""]},
    { value: "Web Security", synonyms: [""]},
    { value: "Cyber Security Social Engineering", synonyms: [""]},
    { value: "Raspberry Pi", synonyms: [""]},
    { value: "PIC Microcontroller", synonyms: [""]},
    { value: "Computer Hardware", synonyms: [""]},
    { value: "Computer Repair and Maintenance", synonyms: [""]},
    { value: "PCB Design", synonyms: [""]},
    { value: "Cell Phone Repair", synonyms: [""]},
    { value: "Verilog HDL Programming", synonyms: [""]},
    { value: "Home Automation", synonyms: [""]},
    { value: "Computer Architecture", synonyms: [""]},
    { value: "Build a Computer", synonyms: [""]},
    { value: "Embedded C", synonyms: [""]},
    { value: "Windows Server", synonyms: [""]},
    { value: "Windows 10", synonyms: [""]},
    { value: "Linux Administration", synonyms: [""]},
    { value: "Active Directory", synonyms: [""]},
    { value: "Linux Command Line", synonyms: [""]},
    { value: "VMware Vsphere", synonyms: [""]},
    { value: "Bash Shell", synonyms: [""]},
    { value: "Shell Scripting", synonyms: [""]},
    { value: "Computer Skills", synonyms: [""]},
    { value: "Server Administration", synonyms: [""]},
    { value: "VirtualBox", synonyms: [""]},
    { value: "Windows 11", synonyms: [""]},
    { value: "IT / Technical Support", synonyms: [""]},
    { value: "Operating System Creation", synonyms: [""]},
    { value: "Linux Kernel", synonyms: [""]},
    { value: "Command Line", synonyms: [""]},
    { value: "Graphic Design", synonyms: [""]},
    { value: "3D Modeling", synonyms: [""]},
    { value: "Adobe Illustrator", synonyms: [""]},
    { value: "After Effects", synonyms: [""]},
    { value: "3ds Max", synonyms: [""]},
    { value: "User Experience Design", synonyms: [""]},
    { value: "Interior Design", synonyms: [""]},
    { value: "3D Animation", synonyms: [""]},
    { value: "Architectural Design", synonyms: [""]},
    { value: "Fashion Design", synonyms: [""]},
    { value: "Logo Design", synonyms: [""]},
    { value: "Cinema 4D", synonyms: [""]},
    { value: "Adobe XD", synonyms: [""]},
    { value: "Design Thinking", synonyms: [""]},
    { value: "Product Design", synonyms: [""]},
    { value: "Usability Testing", synonyms: [""]},
    { value: "UX Writing", synonyms: [""]},
    { value: "Sketch Software", synonyms: [""]},
    { value: "Axure RP", synonyms: [""]},
    { value: "Information Architecture", synonyms: [""]},
    { value: "Professional Portfolio", synonyms: [""]},
    { value: "Web Accessibility", synonyms: [""]},
    { value: "Color Theory", synonyms: [""]},
    { value: "Pixel Art", synonyms: [""]},
    { value: "Game Art", synonyms: [""]},
    { value: "Character Design", synonyms: [""]},
    { value: "Digital Painting", synonyms: [""]},
    { value: "Photoshop", synonyms: [""]},
    { value: "Game Texturing", synonyms: [""]},
    { value: "Game Asset Creation", synonyms: [""]},
    { value: "Substance Painter", synonyms: [""]},
    { value: "VFX Visual Effects", synonyms: [""]},
    { value: "2D Animation", synonyms: [""]},
    { value: "Character Animation", synonyms: [""]},
    { value: "3D Rendering", synonyms: [""]},
    { value: "Motion Graphics", synonyms: [""]},
    { value: "3D Printing", synonyms: [""]},
    { value: "Fusion 360", synonyms: [""]},
    { value: "Houdini Software", synonyms: [""]},
    { value: "3D Sculpting", synonyms: [""]},
    { value: "Character Modeling", synonyms: [""]},
    { value: "Photorealistic Rendering", synonyms: [""]},
    { value: "3D Texturing", synonyms: [""]},
    { value: "Autodesk Inventor", synonyms: [""]},
    { value: "Diagnostics (Basics,", synonyms: [""]},
    { value: "Debugging, Performance)", synonyms: [""]},
    { value: "HTTP(S)/TCP – sockets.io", synonyms: [""]},
    { value: "Child Processes", synonyms: [""]},
    { value: "Buffer and Streams", synonyms: [""]},
    { value: "Error Handling", synonyms: [""]},
    { value: "File System", synonyms: [""]},
    { value: "Control flow (Async tasks,", synonyms: [""]},
    { value: "Module system", synonyms: [""]},
    { value: "IA – Neural Networks", synonyms: [""]},
    { value: "Asterisk connections", synonyms: [""]},
    { value: "Java", synonyms: [""]},
    { value: "Node", synonyms: [""]},
    { value: "Drupal", synonyms: [""]},
    { value: "JDeveloper", synonyms: [""]},
    { value: "UFT", synonyms: [""]},
    { value: "Slack", synonyms: [""]},
    { value: "Fuel", synonyms: [""]},
    { value: "Smack", synonyms: [""]},
    { value: "HTML & CSS", synonyms: [""]},
    { value: "Promo-materials", synonyms: [""]},
    { value: "C++", synonyms: [""]},
    { value: "Coaching", synonyms: [""]},
    { value: "Payroll", synonyms: [""]},
    { value: "WCF", synonyms: [""]},
    { value: "Support.Infrastructure", synonyms: [""]},
    { value: "DE/Mobile", synonyms: [""]},
    { value: "DevOps.CI/CD", synonyms: [""]},
    { value: "DevOps.IaC", synonyms: [""]},
    { value: "DevOps.Containers", synonyms: [""]},
    { value: "CloudFront", synonyms: [""]},
    { value: "CloudWatch", synonyms: [""]},
    { value: "CloudFormation", synonyms: [""]},
    { value: "CloudTrail", synonyms: [""]},
    { value: "IoT", synonyms: [""]},
    { value: "Qase", synonyms: [""]},
    { value: "Interview", synonyms: [""]},
    { value: "Research-Analysis", synonyms: [""]},
    { value: "Innovator", synonyms: [""]},
    { value: "GameDev", synonyms: [""]},
    { value: "TensorFlow", synonyms: [""]},
    { value: "Sensors", synonyms: [""]},
    { value: "Blockchain", synonyms: [""]},
    { value: "AT/Blockchain", synonyms: [""]},
    { value: "Sales", synonyms: [""]},
    { value: "Salesforce", synonyms: [""]},
    { value: "NodeJs", synonyms: [""]},
    { value: "React", synonyms: [""]},
    { value: "Native Scripts", synonyms: [""]},
    { value: "Vue", synonyms: [""]},
    { value: "Sailsjs", synonyms: [""]},
    { value: "Expressjs", synonyms: [""]},
    { value: "Bull", synonyms: [""]},
    { value: "Redis", synonyms: [""]},
    { value: "Apigility", synonyms: [""]},
    { value: "Mysql", synonyms: [""]},
    { value: "Bootstrap", synonyms: [""]},
    { value: "Laravel", synonyms: [""]},
    { value: "Microservice", synonyms: [""]},
    { value: "SCRUM", synonyms: [""]},
    { value: "BigQuery", synonyms: [""]},
    { value: "Dataflow", synonyms: [""]},
    { value: "Operations", synonyms: [""]},
    { value: "Anthos", synonyms: [""]},
    { value: "AutoML", synonyms: [""]},
    { value: "Dialogflow", synonyms: [""]},
    { value: "AppSheet", synonyms: [""]},
    { value: "HealthAPIx", synonyms: [""]},
    { value: "Batch", synonyms: [""]},
    { value: "Recommender", synonyms: [""]},
    { value: "Containers", synonyms: [""]},
    { value: "Knative", synonyms: [""]},
    { value: "Looker", synonyms: [""]},
    { value: "Dataproc", synonyms: [""]},
    { value: "Pub/Sub", synonyms: [""]},
    { value: "Dataprep", synonyms: [""]},
    { value: "Dataplex", synonyms: [""]},
    { value: "BigLake", synonyms: [""]},
    { value: "Firestore", synonyms: [""]},
    { value: "Memorystore", synonyms: [""]},
    { value: "Datastream", synonyms: [""]},
    { value: "Tekton", synonyms: [""]},
    { value: "OpenCue", synonyms: [""]},
    { value: "Firewalls", synonyms: [""]},
    { value: "Vault", synonyms: [""]},
    { value: "VirusTotal", synonyms: [""]},
    { value: "Workflows", synonyms: [""]},
    { value: "Filestore", synonyms: [""]},
    { value: "Cascading", synonyms: [""]},
    { value: "ZKoss", synonyms: [""]},
    { value: "GlassFish", synonyms: [""]},
    { value: "Wildfly", synonyms: [""]},
    { value: "Drools", synonyms: [""]},
    { value: "Infinispan", synonyms: [""]},
    { value: "IText", synonyms: [""]},
    { value: "EHCache", synonyms: [""]},
    { value: "Sax", synonyms: [""]},
    { value: "MyBatis", synonyms: [""]},
    { value: "jBPM", synonyms: [""]},
    { value: "JMonkeyEngine", synonyms: [""]},
    { value: "Jackson", synonyms: [""]},
    { value: "JFreeChart", synonyms: [""]},
    { value: "BioJava", synonyms: [""]},
    { value: "JSoup", synonyms: [""]},
    { value: "Jetty", synonyms: [""]},
    { value: "BlueCove", synonyms: [""]},
    { value: "LWJGL", synonyms: [""]},
    { value: "GeoTools", synonyms: [""]},
    { value: "Neuroph", synonyms: [""]},
    { value: "EclipseLink", synonyms: [""]},
    { value: "JProfiler", synonyms: [""]},
    { value: "JRockit", synonyms: [""]},
    { value: "JSF", synonyms: [""]},
    { value: "Apache PDFBox", synonyms: [""]},
    { value: "JaxP", synonyms: [""]},
    { value: "Thymeleaf", synonyms: [""]},
    { value: "JDom", synonyms: [""]},
    { value: "Jersey", synonyms: [""]},
    { value: "JHipster", synonyms: [""]},
    { value: "Quartz", synonyms: [""]},
    { value: "TestNG", synonyms: [""]},
    { value: "OpenCV", synonyms: [""]},
    { value: "JavAssist", synonyms: [""]},
    { value: "Selenium", synonyms: [""]},
    { value: "OpenCSV", synonyms: [""]},
    { value: "LiquiBase", synonyms: [""]},
    { value: "Elasticsearch", synonyms: [""]},
    { value: "Barracuda", synonyms: [""]},
    { value: "Netty", synonyms: [""]},
    { value: "OrientDB", synonyms: [""]},
    { value: "ORMLite", synonyms: [""]},
    { value: "Hibernate", synonyms: [""]},
    { value: "Deeplearning4j", synonyms: [""]},
    { value: "AppFuse", synonyms: [""]},
    { value: "iBatis", synonyms: [""]},
    { value: "SonarQube", synonyms: [""]},
    { value: "Play", synonyms: [""]},
    { value: "Vertx", synonyms: [""]},
    { value: "HSQLDB", synonyms: [""]},
    { value: "Birt", synonyms: [""]},
    { value: "Selenide", synonyms: [""]},
    { value: "GeoApi", synonyms: [""]},
    { value: "SLF4J", synonyms: [""]},
    { value: "Keycloak", synonyms: [""]},
    { value: "Spock", synonyms: [""]},
    { value: "Akka", synonyms: [""]},
    { value: "JUnit", synonyms: [""]},
    { value: "Mockito", synonyms: [""]},
    { value: "PrimeFaces", synonyms: [""]},
    { value: "Vaadin", synonyms: [""]},
    { value: "Angular", synonyms: [""]},
    { value: "Express", synonyms: [""]},
    { value: "Python", synonyms: [""]},
    { value: "Spring", synonyms: [""]},
    { value: "Django", synonyms: [""]},
    { value: "Flask", synonyms: [""]},
    { value: "Symfony", synonyms: [""]},
    { value: "Gatsby", synonyms: [""]},
    { value: "Sinatra", synonyms: [""]},
    { value: "CakePHP", synonyms: [""]},
    { value: "Horde", synonyms: [""]},
    { value: "Yii", synonyms: [""]},
    { value: "Zend", synonyms: [""]},
    { value: "Zikula", synonyms: [""]},
    { value: "Grails", synonyms: [""]},
    { value: "Web2py", synonyms: [""]},
    { value: "Lumen", synonyms: [""]},
    { value: "TurboGears", synonyms: [""]},
    { value: "Phalcon", synonyms: [""]},
    { value: "FuelPHP", synonyms: [""]},
    { value: "Spark", synonyms: [""]},
    { value: "Grok", synonyms: [""]},
    { value: "Mojolicious", synonyms: [""]},
    { value: "Wicket", synonyms: [""]},
    { value: "Yesod", synonyms: [""]},
    { value: "Nuxt.js", synonyms: [""]},
    { value: "Next.js", synonyms: [""]},
    { value: "Phoenix", synonyms: [""]},
    { value: "CodeIgniter", synonyms: [""]},
    { value: "PHPixie", synonyms: [""]},
    { value: "Javalin", synonyms: [""]},
    { value: "Silex", synonyms: [""]},
    { value: "Ionic", synonyms: [""]},
    { value: "Xamarin", synonyms: [""]},
    { value: "PhoneGap", synonyms: [""]},
    { value: "Corona", synonyms: [""]},
    { value: "Flutter", synonyms: [""]},
    { value: "Appcelerator Titanium", synonyms: [""]},
    { value: "Swiftic", synonyms: [""]},
    { value: "NativeScript", synonyms: [""]},
    { value: "Apache MXNet", synonyms: [""]},
    { value: "ML.NET", synonyms: [""]},
    { value: "Infer.NET", synonyms: [""]},
    { value: "Accord.NET", synonyms: [""]},
    { value: "Chainer", synonyms: [""]},
    { value: "Horovod", synonyms: [""]},
    { value: "Gauge", synonyms: [""]},
    { value: "Pytest", synonyms: [""]},
    { value: "Jest", synonyms: [""]},
    { value: "Mocha", synonyms: [""]},
    { value: "Jasmine", synonyms: [""]},
    { value: "Nightwatch", synonyms: [""]},
    { value: "Protractor", synonyms: [""]},
    { value: "Cypress", synonyms: [""]},
    { value: "TestProject", synonyms: [""]},
    { value: "WebDriverIO", synonyms: [""]},
    { value: "OpenTest", synonyms: [""]},
    { value: "Citrus", synonyms: [""]},
    { value: "Scrapy", synonyms: [""]},
    { value: "Truffle", synonyms: [""]},
    { value: "Embark", synonyms: [""]},
    { value: "Etherlime", synonyms: [""]},
    { value: "Brownie", synonyms: [""]},
    { value: "Exonum", synonyms: [""]},
    { value: "Hyperledger", synonyms: [""]},
    { value: "Corda", synonyms: [""]},
    { value: "MultiChain", synonyms: [""]},
    { value: "Meteor", synonyms: [""]},
    { value: "SiteWhere", synonyms: [""]},
    { value: "Electron", synonyms: [""]},
    { value: "Svelte", synonyms: [""]},
    { value: "Aurelia", synonyms: [""]},
    { value: "Mithril", synonyms: [""]},
    { value: "Bulma", synonyms: [""]},
    { value: "Microdot", synonyms: [""]},
    { value: "Rapidoid", synonyms: [""]},
    { value: "Ktor", synonyms: [""]},
    { value: "Scalatra", synonyms: [""]},
    { value: "PHP", synonyms: [""]},
    { value: "jQuery", synonyms: [""]},
    { value: "Mongodb", synonyms: [""]},
    { value: "Mongoose", synonyms: [""]},
    { value: "sql,", synonyms: [""]},
    { value: "WordPress", synonyms: [""]},
    { value: "CSS", synonyms: [""]},
    { value: "HTML", synonyms: [""]},
    { value: "HTML5", synonyms: [""]},
    { value: "Node.Js", synonyms: [""]},
    { value: "R", synonyms: [""]},
    { value: "Statistics", synonyms: [""]},
    { value: "Pandas", synonyms: [""]},
    { value: "NumPy", synonyms: [""]},
    { value: "PyTorch", synonyms: [""]},
    { value: "PySpark", synonyms: [""]},
    { value: "SQL", synonyms: [""]},
    { value: "Swift", synonyms: [""]},
    { value: "SwiftUI", synonyms: [""]},
    { value: "Firebase", synonyms: [""]},
    { value: "Kotlin", synonyms: [""]},
    { value: "Xcode", synonyms: [""]},
    { value: "Dart", synonyms: [""]},
    { value: "C#", synonyms: [""]},
    { value: "JavaScript", synonyms: [""]},
    { value: "C", synonyms: [""]},
    { value: "Go", synonyms: [""]},
    { value: "Algorithms", synonyms: [""]},
    { value: "MATLAB", synonyms: [""]},
    { value: "Rust", synonyms: [""]},
    { value: "Ruby", synonyms: [""]},
    { value: "Typescript", synonyms: [""]},
    { value: "Scala", synonyms: [""]},
    { value: "Unity", synonyms: [""]},
    { value: "Godot", synonyms: [""]},
    { value: "Blender", synonyms: [""]},
    { value: "Minecraft", synonyms: [""]},
    { value: "MySQL", synonyms: [""]},
    { value: "MongoDB", synonyms: [""]},
    { value: "PL/SQL", synonyms: [""]},
    { value: "SQLite", synonyms: [""]},
    { value: "T-SQL", synonyms: [""]},
    { value: "JMeter", synonyms: [""]},
    { value: "Appium", synonyms: [""]},
    { value: "Postman", synonyms: [""]},
    { value: "Cypress.io", synonyms: [""]},
    { value: "Automation", synonyms: [""]},
    { value: "XPath", synonyms: [""]},
    { value: "Microservices", synonyms: [""]},
    { value: "Docker", synonyms: [""]},
    { value: "DevOps", synonyms: [""]},
    { value: "Agile", synonyms: [""]},
    { value: "Kubernetes", synonyms: [""]},
    { value: "Arduino", synonyms: [""]},
    { value: "Git", synonyms: [""]},
    { value: "GitHub", synonyms: [""]},
    { value: "JIRA", synonyms: [""]},
    { value: "Jenkins", synonyms: [""]},
    { value: "Terraform", synonyms: [""]},
    { value: "Ansible", synonyms: [""]},
    { value: "Cryptography", synonyms: [""]},
    { value: "Firewall", synonyms: [""]},
    { value: "OCP/Kubernetes", synonyms: [""]},
    { value: "Linux", synonyms: [""]},
    { value: "Electronics", synonyms: [""]},
    { value: "PLC", synonyms: [""]},
    { value: "FPGA", synonyms: [""]},
    { value: "Robotics", synonyms: [""]},
    { value: "Microcontroller", synonyms: [""]},
    { value: "VHDL", synonyms: [""]},
    { value: "STM32", synonyms: [""]},
    { value: "ESP32", synonyms: [""]},
    { value: "SystemVerilog", synonyms: [""]},
    { value: "PowerShell", synonyms: [""]},
    { value: "macOS", synonyms: [""]},
    { value: "Ubuntu", synonyms: [""]},
    { value: "Virtualization", synonyms: [""]},
    { value: "CentOS", synonyms: [""]},
    { value: "AutoCAD", synonyms: [""]},
    { value: "Drawing", synonyms: [""]},
    { value: "Canva", synonyms: [""]},
    { value: "SketchUp", synonyms: [""]},
    { value: "Maya", synonyms: [""]},
    { value: "zBrush", synonyms: [""]},
    { value: "Animation", synonyms: [""]},
    { value: "Figma", synonyms: [""]},
    { value: "Prototyping", synonyms: [""]},
    { value: "Gamification", synonyms: [""]},
    { value: "Wireframing", synonyms: [""]},
    { value: "Personas", synonyms: [""]},
    { value: "Inkscape", synonyms: [""]},
    { value: "SOLIDWORKS", synonyms: [""]},
    { value: "Databases", synonyms: [""]},
    { value: "Elementor", synonyms: [""]},
    { value: "Wix", synonyms: [""]},
    { value: "Adalo", synonyms: [""]},
    { value: "WooCommerce", synonyms: [""]},
    { value: "Chatbot", synonyms: [""]},
    { value: "Blogging", synonyms: [""]},
    { value: "Weebly", synonyms: [""]},
    { value: "Pega", synonyms: [""]},
    { value: "Scrum", synonyms: [""]},
    { value: "Cisco", synonyms: [""]},
    { value: "MikroTik", synonyms: [""]},
    { value: "Revit", synonyms: [""]},
    { value: ".NET", synonyms: [""]},
    { value: "2D Art", synonyms: [""]},
    { value: "3D Art", synonyms: [""]},
    { value: "ABAP", synonyms: [""]},
    { value: "Accounting and Financial", synonyms: [""]},
    { value: "ActionScript", synonyms: [""]},
    { value: "ADAM", synonyms: [""]},
    { value: "Adobe AEM/CQ (Day CQ)", synonyms: [""]},
    { value: "Adobe Analytics", synonyms: [""]},
    { value: "Adobe Audience Manager", synonyms: [""]},
    { value: "Adobe Campaign", synonyms: [""]},
    { value: "Adobe Flash", synonyms: [""]},
    { value: "Adobe Target", synonyms: [""]},
    { value: "AEM Forms", synonyms: [""]},
    { value: "Agile Coach", synonyms: [""]},
    { value: "Android", synonyms: [""]},
    { value: "Android Kotlin", synonyms: [""]},
    { value: "Apache Flex (Adobe Flex)", synonyms: [""]},
    { value: "API", synonyms: [""]},
    { value: "Apigee", synonyms: [""]},
    { value: "Appian", synonyms: [""]},
    { value: "Applied Mathematics", synonyms: [""]},
    { value: "Art Direction", synonyms: [""]},
    { value: "Assessment and migration", synonyms: [""]},
    { value: "Automated Testing", synonyms: [""]},
    { value: "Automated Testing in .NET", synonyms: [""]},
    { value: "Automated Testing in Java", synonyms: [""]},
    { value: "Automated Testing in JS", synonyms: [""]},
    { value: "Automated Testing in PHP", synonyms: [""]},
    { value: "Automated Testing in Python", synonyms: [""]},
    { value: "Automated Testing in Ruby", synonyms: [""]},
    { value: "Automation Anywhere", synonyms: [""]},
    { value: "Basis", synonyms: [""]},
    { value: "BI (BO)", synonyms: [""]},
    { value: "BI (BW)", synonyms: [""]},
    { value: "BI (EPM)", synonyms: [""]},
    { value: "BI Analyst", synonyms: [""]},
    { value: "BI Development", synonyms: [""]},
    { value: "BI.MicroStrategy", synonyms: [""]},
    { value: "BI.MS Power BI", synonyms: [""]},
    { value: "BI.Oracle BI EE", synonyms: [""]},
    { value: "BI.Oracle Data Visualization", synonyms: [""]},
    { value: "BI.Qlik", synonyms: [""]},
    { value: "BI.Tableau", synonyms: [""]},
    { value: "BI.TIBCO Spotfire", synonyms: [""]},
    { value: "Biology", synonyms: [""]},
    { value: "BizTalk", synonyms: [""]},
    { value: "Blackberry", synonyms: [""]},
    { value: "Blue Prism", synonyms: [""]},
    { value: "Borland Delphi", synonyms: [""]},
    { value: "BPM", synonyms: [""]},
    { value: "Brand Design", synonyms: [""]},
    { value: "BrightScript", synonyms: [""]},
    { value: "Business process management (BPM)", synonyms: [""]},
    { value: "C (including Ansi C)", synonyms: [""]},
    { value: "Censhare", synonyms: [""]},
    { value: "Chemistry", synonyms: [""]},
    { value: "Cloud.AWS", synonyms: [""]},
    { value: "Cloud.Azure", synonyms: [""]},
    { value: "Cloud.Google", synonyms: [""]},
    { value: "Cloud.OpenStack", synonyms: [""]},
    { value: "Cloud.VMWare", synonyms: [""]},
    { value: "Cloud/Grid computing", synonyms: [""]},
    { value: "Cognos BI", synonyms: [""]},
    { value: "Community", synonyms: [""]},
    { value: "Content Authoring", synonyms: [""]},
    { value: "Content Creation", synonyms: [""]},
    { value: "Content Management", synonyms: [""]},
    { value: "Content Strategy", synonyms: [""]},
    { value: "CRM", synonyms: [""]},
    { value: "Crowd Operations", synonyms: [""]},
    { value: "Data Analytics and Visualization", synonyms: [""]},
    { value: "Data integration and hybrid cloud", synonyms: [""]},
    { value: "Data Integration DB and ETL", synonyms: [""]},
    { value: "Data Quality Engineering", synonyms: [""]},
    { value: "Data Solution Architecture and Modelling", synonyms: [""]},
    { value: "Data Technology Consulting", synonyms: [""]},
    { value: "DBMS Engineering", synonyms: [""]},
    { value: "Delivery Management", synonyms: [""]},
    { value: "Dell Boomi AtomSphere", synonyms: [""]},
    { value: "DevOps.BigData", synonyms: [""]},
    { value: "DevOps.Data", synonyms: [""]},
    { value: "DevOps.Operational Intelligence", synonyms: [""]},
    { value: "DevOps.Scripting", synonyms: [""]},
    { value: "DevOps.Security", synonyms: [""]},
    { value: "Digital Client Engagement", synonyms: [""]},
    { value: "Digital Prototyping", synonyms: [""]},
    { value: "Documentum", synonyms: [""]},
    { value: "DW Development", synonyms: [""]},
    { value: "DW.MS SQL Server", synonyms: [""]},
    { value: "DW.Oracle", synonyms: [""]},
    { value: "DW.Teradata", synonyms: [""]},
    { value: "DWBI", synonyms: [""]},
    { value: "eLearning", synonyms: [""]},
    { value: "Electrical Engineering", synonyms: [""]},
    { value: "Electronics Engineering", synonyms: [""]},
    { value: "EntApps.Microsoft Business Solution", synonyms: [""]},
    { value: "Enterprise Analytics", synonyms: [""]},
    { value: "Enterprise Search", synonyms: [""]},
    { value: "Envisioning", synonyms: [""]},
    { value: "Episerver", synonyms: [""]},
    { value: "Erlang", synonyms: [""]},
    { value: "ESB", synonyms: [""]},
    { value: "ETL.Alteryx", synonyms: [""]},
    { value: "ETL.IBM DataStage", synonyms: [""]},
    { value: "ETL.Informatica", synonyms: [""]},
    { value: "ETL.SSIS", synonyms: [""]},
    { value: "FICO", synonyms: [""]},
    { value: "Financial modeling", synonyms: [""]},
    { value: "Functional testing", synonyms: [""]},
    { value: "Functional Testing in Mobile", synonyms: [""]},
    { value: "Go Language", synonyms: [""]},
    { value: "HANA Platform", synonyms: [""]},
    { value: "Hana XS", synonyms: [""]},
    { value: "Haskell", synonyms: [""]},
    { value: "HCM", synonyms: [""]},
    { value: "Healthcare Strategy", synonyms: [""]},
    { value: "Human Factors", synonyms: [""]},
    { value: "IBM Sterling", synonyms: [""]},
    { value: "IBM Websphere Commerce", synonyms: [""]},
    { value: "Industrial Design", synonyms: [""]},
    { value: "Informix", synonyms: [""]},
    { value: "Innovation Strategy", synonyms: [""]},
    { value: "Interim - Integration Related", synonyms: [""]},
    { value: "iOS Objective-C", synonyms: [""]},
    { value: "iOS Swift", synonyms: [""]},
    { value: "IT Service Management (ITSM)", synonyms: [""]},
    { value: "Jurisprudence", synonyms: [""]},
    { value: "Language Instruction", synonyms: [""]},
    { value: "Learning Experience Design", synonyms: [""]},
    { value: "Learning Operations", synonyms: [""]},
    { value: "Learning Programs Management", synonyms: [""]},
    { value: "LMS Administration", synonyms: [""]},
    { value: "Logistics", synonyms: [""]},
    { value: "M&A Integration", synonyms: [""]},
    { value: "Mac App Development", synonyms: [""]},
    { value: "Magento", synonyms: [""]},
    { value: "Mainframe", synonyms: [""]},
    { value: "Management", synonyms: [""]},
    { value: "Math", synonyms: [""]},
    { value: "MDM", synonyms: [""]},
    { value: "Mechanical Engineering", synonyms: [""]},
    { value: "Medicine", synonyms: [""]},
    { value: "Microsoft Dynamics AX", synonyms: [""]},
    { value: "Microsoft Dynamics CRM", synonyms: [""]},
    { value: "Microsoft Dynamics NAV", synonyms: [""]},
    { value: "Microsoft OLAP Services", synonyms: [""]},
    { value: "Microsoft SharePoint", synonyms: [""]},
    { value: "Microsoft SharePoint Administration", synonyms: [""]},
    { value: "Microsoft SQL Server", synonyms: [""]},
    { value: "Mobility", synonyms: [""]},
    { value: "Movex M3", synonyms: [""]},
    { value: "MS Windows User", synonyms: [""]},
    { value: "N/A", synonyms: [""]},
    { value: "Node.js", synonyms: [""]},
    { value: "Office Management", synonyms: [""]},
    { value: "OpenText ECM", synonyms: [""]},
    { value: "OpenWay Way4", synonyms: [""]},
    { value: "Oracle", synonyms: [""]},
    { value: "Oracle BI", synonyms: [""]},
    { value: "Oracle Commerce", synonyms: [""]},
    { value: "Other", synonyms: [""]},
    { value: "Other Cross-Platform", synonyms: [""]},
    { value: "PCI (Payment Card Industry)", synonyms: [""]},
    { value: "PEGA", synonyms: [""]},
    { value: "People Experience and Programs", synonyms: [""]},
    { value: "People Operations", synonyms: [""]},
    { value: "People Partnership and Advisory", synonyms: [""]},
    { value: "Performance testing", synonyms: [""]},
    { value: "Perl", synonyms: [""]},
    { value: "Pharmacology", synonyms: [""]},
    { value: "Physical Prototyping", synonyms: [""]},
    { value: "Physics", synonyms: [""]},
    { value: "Pipeline Pilot", synonyms: [""]},
    { value: "PLM", synonyms: [""]},
    { value: "Portal", synonyms: [""]},
    { value: "Powerbuilder", synonyms: [""]},
    { value: "Private cloud", synonyms: [""]},
    { value: "Progress", synonyms: [""]},
    { value: "Quantitative Analysis", synonyms: [""]},
    { value: "Quantitative Business", synonyms: [""]},
    { value: "R Language", synonyms: [""]},
    { value: "RubyOnRails", synonyms: [""]},
    { value: "Salesforce Commerce Cloud (B2B - CloudCraze)", synonyms: [""]},
    { value: "Salesforce Commerce Cloud (B2C - Demandware)", synonyms: [""]},
    { value: "Salesforce Integration Cloud (MuleSoft)", synonyms: [""]},
    { value: "SAP (Others)", synonyms: [""]},
    { value: "SAP Commerce Cloud (Hybris Commerce)", synonyms: [""]},
    { value: "SAP Customer Data Cloud (Gigya)", synonyms: [""]},
    { value: "SAP Customer Experience (C/4HANA, Hybris – Other)", synonyms: [""]},
    { value: "SAP Hybris As A Service (YaaS)", synonyms: [""]},
    { value: "SAP Marketing Cloud (Hybris Marketing)", synonyms: [""]},
    { value: "SAP Revenue Cloud (Hybris Billing)", synonyms: [""]},
    { value: "SAP Sales Cloud & SAP Service Cloud (Hybris Cloud For Customer)", synonyms: [""]},
    { value: "SAP Sales Cloud CPQ & SPM (CallidusCloud CPQ & Commissions)", synonyms: [""]},
    { value: "SAP.C/4HANA.Marketing Cloud", synonyms: [""]},
    { value: "SAP.C/4HANA.Revenue Cloud", synonyms: [""]},
    { value: "SAP.C/4HANA.Sales Cloud&SAP Service Cloud", synonyms: [""]},
    { value: "SAP.C4 Hana", synonyms: [""]},
    { value: "SAP.Cloud platform", synonyms: [""]},
    { value: "SAP.HANA Platform", synonyms: [""]},
    { value: "SAP.Java", synonyms: [""]},
    { value: "SAP.SAPUI5", synonyms: [""]},
    { value: "Scrum Master", synonyms: [""]},
    { value: "SDL Tridion/Web", synonyms: [""]},
    { value: "Security Engineering", synonyms: [""]},
    { value: "SET.BigData", synonyms: [""]},
    { value: "SET.Embedded", synonyms: [""]},
    { value: "SET.HPC", synonyms: [""]},
    { value: "SET.Java", synonyms: [""]},
    { value: "SET.Java.BigData", synonyms: [""]},
    { value: "SET.Java.Microservices", synonyms: [""]},
    { value: "SET.Java.Mobile", synonyms: [""]},
    { value: "SET.Java.Web & Desktop", synonyms: [""]},
    { value: "SET.JavaScript", synonyms: [""]},
    { value: "SET.JavaScript.Microservices", synonyms: [""]},
    { value: "SET.JavaScript.Mobile", synonyms: [""]},
    { value: "SET.JavaScript.Web & Desktop", synonyms: [""]},
    { value: "SET.Microservices", synonyms: [""]},
    { value: "SET.Mobile", synonyms: [""]},
    { value: "SET.NET", synonyms: [""]},
    { value: "SET.NET.Microservices", synonyms: [""]},
    { value: "SET.NET.Web & Desktop", synonyms: [""]},
    { value: "SET.Python", synonyms: [""]},
    { value: "SET.Python.Big Data", synonyms: [""]},
    { value: "SET.Python.Embedded", synonyms: [""]},
    { value: "SET.Python.HPC", synonyms: [""]},
    { value: "SET.Python.Microservices", synonyms: [""]},
    { value: "SET.Python.Mobile", synonyms: [""]},
    { value: "SET.Python.Web & Desktop", synonyms: [""]},
    { value: "SET.Web&Desktop", synonyms: [""]},
    { value: "Shopify", synonyms: [""]},
    { value: "Siebel CRM", synonyms: [""]},
    { value: "Sitecore", synonyms: [""]},
    { value: "SOA", synonyms: [""]},
    { value: "Social Media Marketing", synonyms: [""]},
    { value: "Software Engineering Process Group (SEPG)", synonyms: [""]},
    { value: "Space Design", synonyms: [""]},
    { value: "Splunk", synonyms: [""]},
    { value: "Staffing", synonyms: [""]},
    { value: "Statistical Analysis and Modeling", synonyms: [""]},
    { value: "Strategic Consulting", synonyms: [""]},
    { value: "Support.Application", synonyms: [""]},
    { value: "Support.Data", synonyms: [""]},
    { value: "Support.Users", synonyms: [""]},
    { value: "Systems Engineering", synonyms: [""]},
    { value: "Talent Acquisition", synonyms: [""]},
    { value: "Technology Consulting", synonyms: [""]},
    { value: "Training and Development", synonyms: [""]},
    { value: "Training Delivery", synonyms: [""]},
    { value: "Travel", synonyms: [""]},
    { value: "Travel Management", synonyms: [""]},
    { value: "UI/UX Art", synonyms: [""]},
    { value: "UIPath", synonyms: [""]},
    { value: "Unity Development", synonyms: [""]},
    { value: "Unix", synonyms: [""]},
    { value: "UX", synonyms: [""]},
    { value: "Vector Art", synonyms: [""]},
    { value: "Visual Basic", synonyms: [""]},
    { value: "Web Security testing", synonyms: [""]},
    { value: "Windows", synonyms: [""]},
    { value: "WorkFusion", synonyms: [""]},
    { value: "Writing Technical Documentation (English)", synonyms: [""]},
    { value: "XI/PI", synonyms: [""]},
    { value: "XML/XSL/XSLT", synonyms: [""]}
]
// {
//   EVENT_CUSTOMER_CONNECTED: 'customer connected',
//   EVENT_CUSTOMER_DISCONNECTED: 'customer disconnected',
//   EVENT_CUSTOMER_MESSAGE: 'customer message',
//   EVENT_TO_CUSTOMER_MESSAGE: 'message to customer',
//   EVENT_OPERATOR_MESSAGE: 'operator message',
//   EVENT_OPERATOR_REQUESTED: 'operator requested',
//   EVENT_SYSTEM_ERROR: 'system error',
//   EVENT_DISCONNECT: 'disconnect',

//   CONTEXT_OPERATOR_REQUEST: 'operator_request',

//   OPERATOR_GREETING: `Hello, I'm a human. How can I help you?`
// };
